[store]
dir = "target/nextest"

[profile.default]
fail-fast = true
# Kill any test that hangs longer than 60s.
slow-timeout = { period = "60s", terminate-after = 2 }

[profile.ci]
fail-fast = false
retries = 1
slow-timeout = { period = "60s", terminate-after = 2 }
